TYPO3:
  Form:
    presets:
      default:
        finisherPresets:
          'UpAssist.FormEnhancers:Email':
            implementationClassName: 'UpAssist\FormEnhancers\Finishers\EmailFinisher'
          'UpAssist.FormEnhancers:Redirect':
            implementationClassName: 'UpAssist\FormEnhancers\Finishers\NodeRedirectFinisher'
